[workspace]
resolver = "3"
members = [
    "powersync",
    "powersync_test_utils",
    "examples/egui_todolist"
]

[workspace.package]
repository = "https://github.com/powersync-ja/powersync-native"
